### PR TITLE
分岐の1つでbBcCメトリクスを計算する

### PR DESCRIPTION
**Pull request by MaineK00n**
## WHY
- 分岐の一つひとつもTP候補となるべき

## WHAT
- 分岐の一つひとつに対して，bBcCメトリクスを計算して，TP候補とする．

## REF
#53

### CODE REVIEW

**Comment by MaineK00n** [comment]
```bash
$ ./htpi --mode 0 -n 3 s27
line:    1 , D:       0.000000 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:    2 , D:       1.000000 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:    3 , D:       1.000000 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:    4 , D:       1.000000 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:    5 , D:       8.453615 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:    6 , D:       1.000000 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:    7 , D:       1.000000 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:    8 , D:       1.000000 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:    9 , D:       2.000000 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:   10 , D:       8.453615 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:   11 , D:       4.419753 , b:       3.276596 , B:       0.000000 , c:       0.409374 , C:       0.000000 , TPI_flag:0
line:   12 , D:       7.366137 , b:       0.000000 , B:       5.371734 , c:       0.000000 , C:       0.000002 , TPI_flag:1
line:   13 , D:       4.767901 , b:       0.000000 , B:       8.216026 , c:       0.000000 , C:       0.000004 , TPI_flag:1
line:   14 , D:      13.134038 , b:       1.000000 , B:       0.000000 , c:       0.000001 , C:       0.000000 , TPI_flag:0
line:   15 , D:       8.807054 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:   16 , D:      16.134038 , b:       2.688836 , B:       0.000000 , c:       0.000001 , C:       0.000000 , TPI_flag:1
line:   17 , D:       4.000000 , b:       4.939430 , B:       0.000000 , c:       0.617126 , C:       0.000000 , TPI_flag:0
line:   18 , D:       6.285715 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:   19 , D:       1.419753 , b:       0.000000 , B:       1.000000 , c:       0.000000 , C:       0.301030 , TPI_flag:0
line:   20 , D:       2.580247 , b:       4.117552 , B:       0.000000 , c:       1.239507 , C:       0.000000 , TPI_flag:0
line:   21 , D:       3.651852 , b:       2.276596 , B:       0.000000 , c:       0.284435 , C:       0.000000 , TPI_flag:0
line:   22 , D:       2.767901 , b:       1.000000 , B:       0.000000 , c:       0.124939 , C:       0.000000 , TPI_flag:0
line:   23 , D:       4.226808 , b:       2.688836 , B:       0.000000 , c:       0.000001 , C:       0.000000 , TPI_flag:0
line:   24 , D:       8.453615 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:   25 , D:       6.453615 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:   26 , D:       2.714285 , b:       3.939430 , B:       0.000000 , c:       0.492187 , C:       0.000000 , TPI_flag:0
line:   27 , D:       3.285715 , b:       1.000000 , B:       0.000000 , c:       0.124939 , C:       0.000000 , TPI_flag:0
```

**Comment by MaineK00n** [comment]
ベンチマーク回路で動かしたら，データ（TPIリスト）に変更はありませんでした…

**Comment by MaineK00n** [comment]
> 
> 
> ベンチマーク回路で動かしたら，データ（TPIリスト）に変更はありませんでした…

これはあやしそう

**Comment by MaineK00n** [comment]
ここにFANを追加したり，しなければならない
```C
// select TPI flow
  // create gate_list(AND,OR,NAND,NOR,XOR,XNOR)
  int gate_list[gate_num];
  make_gate_list(gate_list);
```

**Comment by MaineK00n** [comment]
ほとんどの信号線(AND, NAND, OR, NOR, XOR, XNOR, FAN)で計算しているので，bBcCメトリクスの計算時のフローと，TPI選択フローを見直すべき

**Comment by Aono082** [comment]
リファレンス作ってて思ったけど
tp挿入後の再計算の順番がめちゃくちゃやな

正確にやるなら
可制御性→可観測性→故障伝搬数→bBcC
けど今は
bBcC→可制御性(cC含む)→可観測性→故障伝搬数
になってる。

いまのままやと、TP制御点で可制御性を変更した後の観測性と故障伝搬数が
正確にbB計算に活かされてないと思う。
直すべき？

**Comment by MaineK00n** [comment]
> リファレンス作ってて思ったけど
> tp挿入後の再計算の順番がめちゃくちゃやな
> 
> 正確にやるなら
> 可制御性→可観測性→故障伝搬数→bBcC
> けど今は
> bBcC→可制御性(cC含む)→可観測性→故障伝搬数
> になってる。
> 
> いまのままやと、TP制御点で可制御性を変更した後の観測性と故障伝搬数が
> 正確にbB計算に活かされてないと思う。
> 直すべき？

これって意図的にこうするって話になったのでは？

**Comment by Aono082** [comment]
何の意図があったか覚えてないな
故障伝搬数と観測性の計算は論文にも書かれてないから
取ってつけたように入れ込んだ気がする

**Comment by MaineK00n** [comment]
この方針でやるって言ったのでは？
確かに故障伝搬数と観測性に関しては私達が追加したものだとは思いますが．

https://github.com/ehimetakahashilab/Hybrid-TPI/issues/32

**Comment by Aono082** [comment]
方針はこれやったけど、リファレンス作りよって違和感しかない
可制御性の変更後の値がbBcCに反映されないまま次のTP選定に入ってる

この方針のフローを説明しようとしても
うまく話せないで

**Comment by MaineK00n** [comment]
方針決めたのは私ではないわけですが？

**Comment by MaineK00n** [comment]
私は可制御性変更から，可観測性，故障伝搬数を更新したあとに，bBcCの計算をするべきだと言いましたが

**Comment by Aono082** [comment]
言いはしてるかもしれんが、アルゴリズムに全く反映されてない

bBcC→可制御性(cC含む)→可観測性→故障伝搬数
再計算後のフローはこっちに直していい？

**Comment by Aono082** [comment]
違った
こっち
可制御性→可観測性→故障伝搬数→bBcC

**Comment by MaineK00n** [comment]
> 言いはしてるかもしれんが、アルゴリズムに全く反映されてない

ここに関しては，却下されたわけですが？

> 可制御性→可観測性→故障伝搬数→bBcC

私はいいと思いますが，おそらく調整が必要だと思います．
今の再計算はTP選択した信号線からメトリクス値に変更がある限り，
バックトレースしながら再計算を行っているはずですが，
可制御性や可観測性，故障伝搬数が変わった中でも，
今まで通りのbBcCメトリクス再計算で問題ないでしょうか？

**Comment by Aono082** [comment]
計算するbBの範囲が増えるくらい？
それだけなら問題ないと思う

**Comment by MaineK00n** [comment]
> 計算するbBの範囲が増えるくらい？
> それだけなら問題ないと思う

可制御性と故障伝搬数が変わるので，計算範囲は大きくなると思うんですけど，
bBcCメトリクスの再計算のスタートはTP選択した信号線からで，
バックトレース内のbBcCメトリクスしか更新しないということで大丈夫ですか？

**Comment by Aono082** [comment]
メンターの論文ではbBは後方に向かって再計算を行う
とあるけん、それでいいと思う

**Comment by MaineK00n** [comment]
それだと再計算の位置を変更させるだけで済みそうな気がする

**Comment by Aono082** [comment]
そうだよ

**Comment by Aono082** [comment]
while (tpi_num < options.max_tpi_num)
  {
    int head = tpi_num;
    selct_tpi(tpi_list, &tpi_num, gate_list);

    for (int i = head; i < tpi_num; i++)
    {
      recalc_Controllability(tpi_list[i]);
    }
    // //COP値(可観測性)cop_O計算
    calc_Observability(bt_trace);

    // //故障の伝搬数D計算
    calc_flt_propagation(ft_trace);

    for (int i = head; i < tpi_num; i++)
    {
      recalcbBcCMetrics(tpi_list[i], blocks);
    }
    prn_FF();
  }

**Comment by MaineK00n** [comment]
> そうだよ

bBcCメトリクスの再計算の位置とかが気になっていたので
あくまでTPからバックトレースの範囲か，
回路全体(可制御性，故障伝搬数の更新範囲がわかりにくいので)の再計算を行うべきかで迷っていた

**Comment by Aono082** [comment]
FF,copo,cop1,b,B,c,C
   1,0.500000,,0.500000,,0.000000,,0.000000,,0.000000,,0.000000,,
   2,0.500000,,0.500000,,0.000000,,0.000000,,0.000000,,0.000000,,
   3,0.500000,,0.500000,,0.000000,,0.000000,,0.000000,,0.000000,,
   4,0.500000,,0.500000,,0.000000,,0.000000,,0.000000,,0.000000,,
   5,0.112864,,0.887136,,0.000000,,0.000000,,0.000000,,0.000000,,
   6,0.545968,,0.454032,,0.000000,,0.000000,,0.000000,,0.000000,,
   7,0.808064,,0.191936,,0.000000,,0.000000,,0.000000,,0.000000,,
   8,0.622266,,0.377734,,0.000000,,0.000000,,0.000000,,0.000000,,
   9,0.500000,,0.500000,,0.000000,,0.000000,,0.000000,,0.000000,,
  10,0.112864,,0.887136,,0.000000,,0.000000,,0.000000,,0.000000,,
  11,0.904032,,0.095968,,3.404181,,0.000000,,0.149158,,0.000000,,
  12,0.622758,,0.377242,,0.000000,,5.371822,,0.000000,,2.274321,,
  13,0.452016,,0.547984,,0.000000,,8.149614,,0.000000,,2.128941,,
  14,0.206723,,0.793277,,1.000000,,0.000000,,0.684612,,0.000000,,
  15,0.556432,,0.443568,,0.000000,,0.000000,,0.000000,,0.000000,,
  16,0.887136,,0.112864,,2.882746,,0.000000,,0.149931,,0.000000,,
  17,0.688867,,0.311133,,4.745432,,0.000000,,0.768118,,0.000000,,
  18,0.655566,,0.344434,,0.000000,,0.000000,,0.000000,,0.000000,,
  19,0.500000,,0.500000,,0.000000,,1.000000,,0.000000,,0.301030,,
  20,0.500000,,0.500000,,4.104287,,0.000000,,1.235514,,0.000000,,
  21,0.904032,,0.095968,,2.404181,,0.000000,,0.105342,,0.000000,,
  22,0.904032,,0.095968,,1.000000,,0.000000,,0.043816,,0.000000,,
  23,0.887136,,0.112864,,2.882746,,0.000000,,0.149931,,0.000000,,
  24,0.887136,,0.112864,,0.000000,,0.000000,,0.000000,,0.000000,,
  25,0.887136,,0.112864,,0.000000,,0.000000,,0.000000,,0.000000,,
  26,0.688867,,0.311133,,3.745432,,0.000000,,0.606253,,0.000000,,
  27,0.688867,,0.311133,,1.000000,,0.000000,,0.161865,,0.000000,,

FF,copo,cop1,b,B,c,C　-TP 12-
   1,0.500000,,0.500000,,0.000000,,0.000000,,0.000000,,0.000000,,
   2,0.500000,,0.500000,,0.000000,,0.000000,,0.000000,,0.000000,,
   3,0.500000,,0.500000,,0.000000,,0.000000,,0.000000,,0.000000,,
   4,0.500000,,0.500000,,0.000000,,0.000000,,0.000000,,0.000000,,
   5,0.112864,,0.887136,,0.000000,,0.000000,,0.000000,,0.000000,,
   6,0.545968,,0.454032,,0.000000,,0.000000,,0.000000,,0.000000,,
   7,0.808064,,0.191936,,0.000000,,0.000000,,0.000000,,0.000000,,
   8,0.622266,,0.377734,,0.000000,,0.000000,,0.000000,,0.000000,,
   9,0.500000,,0.500000,,0.000000,,0.000000,,0.000000,,0.000000,,
  10,0.299181,,0.700819,,0.000000,,0.000000,,0.000000,,0.000000,,
  11,0.904032,,0.095968,,3.404181,,0.000000,,0.149158,,0.000000,,
  12,0.000001,,0.999999,,0.000000,,5.371822,,0.000000,,0.000002,,
  13,0.452016,,0.547984,,0.000000,,8.149614,,0.000000,,2.128941,,
  14,0.547983,,0.452017,,1.000000,,0.000000,,0.261233,,0.000000,,
  15,0.649591,,0.350409,,0.000000,,0.000000,,0.000000,,0.000000,,
  16,0.700819,,0.299181,,2.882746,,0.000000,,0.445080,,0.000000,,
  17,0.688867,,0.311133,,3.810060,,0.000000,,0.616714,,0.000000,,
  18,0.655566,,0.344434,,0.000000,,0.000000,,0.000000,,0.000000,,
  19,0.500000,,0.500000,,0.000000,,1.000000,,0.000000,,0.301030,,
  20,0.500000,,0.500000,,4.104287,,0.000000,,1.235514,,0.000000,,
  21,0.904032,,0.095968,,2.404181,,0.000000,,0.105342,,0.000000,,
  22,0.904032,,0.095968,,1.000000,,0.000000,,0.043816,,0.000000,,
  23,0.700819,,0.299181,,2.882746,,0.000000,,0.445080,,0.000000,,
  24,0.700819,,0.299181,,0.000000,,0.000000,,0.000000,,0.000000,,
  25,0.700819,,0.299181,,0.000000,,0.000000,,0.000000,,0.000000,,
  26,0.688867,,0.311133,,2.810060,,0.000000,,0.454849,,0.000000,,
  27,0.688867,,0.311133,,1.000000,,0.000000,,0.161865,,0.000000,,

**Comment by Aono082** [comment]
[s27_reference_multi(hybrid_init_ave).xlsx](https://github.com/ehimetakahashilab/Hybrid-TPI/files/3895142/s27_reference_multi.hybrid_init_ave.xlsx)

**Comment by Aono082** [comment]
よさそう

あとは、分岐先をTPに選ぶことができるかどうか
分岐先が選ばれたとき再計算はうまくいくがどうか
を見る

**Comment by Aono082** [comment]
aono@skunk:~/github_workspace/Hybrid-TPI$ ./htpi --mode 1 -n 3 s27
FF,copo,cop1,b,B,c,C
   1,0.500000,,0.500000,,0.893372,,0.000000,,0.000000,,0.000000,,0.000000,,0.000000,,
   2,0.500000,,0.500000,,0.395285,,1.000000,,0.000000,,0.000000,,0.000000,,0.000000,,
   3,0.500000,,0.500000,,0.688867,,1.000000,,0.000000,,0.000000,,0.000000,,0.000000,,
   4,0.500000,,0.500000,,0.186196,,1.000000,,0.000000,,0.000000,,0.000000,,0.000000,,
   5,0.112864,,0.887136,,1.000000,,8.208574,,0.000000,,0.000000,,0.000000,,0.000000,,
   6,0.545968,,0.454032,,1.000000,,1.000000,,0.000000,,0.000000,,0.000000,,0.000000,,
   7,0.808064,,0.191936,,1.000000,,1.000000,,0.000000,,0.000000,,0.000000,,0.000000,,
   8,0.622266,,0.377734,,1.000000,,1.000000,,0.000000,,0.000000,,0.000000,,0.000000,,
   9,0.500000,,0.500000,,0.893372,,2.000000,,0.000000,,0.000000,,0.000000,,0.000000,,
  10,0.112864,,0.887136,,1.000000,,8.208574,,0.000000,,0.000000,,0.000000,,0.000000,,
  11,0.904032,,0.095968,,0.287853,,4.117254,,3.404181,,0.000000,,0.149158,,0.000000,,
  12,0.622758,,0.377242,,0.299182,,7.149614,,0.000000,,5.371822,,0.000000,,2.274321,,
  13,0.452016,,0.547984,,0.205962,,4.371822,,0.000000,,8.149614,,0.000000,,2.128941,,
  14,0.206723,,0.793277,,0.545968,,12.521436,,1.000000,,0.000000,,0.684612,,0.000000,,
  15,0.556432,,0.443568,,1.000000,,8.987033,,0.000000,,0.000000,,0.000000,,0.000000,,
  16,0.887136,,0.112864,,1.000000,,15.521436,,2.882746,,0.000000,,0.149931,,0.000000,,
  17,0.688867,,0.311133,,0.635235,,4.000000,,4.745432,,0.000000,,0.768118,,0.000000,,
  18,0.655566,,0.344434,,1.000000,,6.595819,,0.000000,,0.000000,,0.000000,,0.000000,,
  19,0.500000,,0.500000,,0.055249,,1.117254,,0.000000,,1.000000,,0.000000,,0.301030,,
  20,0.500000,,0.500000,,0.887136,,2.882746,,4.104287,,0.000000,,1.235514,,0.000000,,
  21,0.904032,,0.095968,,0.206096,,3.745432,,2.404181,,0.000000,,100.000000,,0.000000,,
  22,0.904032,,0.095968,,0.102981,,2.371822,,1.000000,,0.000000,,0.043816,,0.000000,,
  23,0.887136,,0.112864,,0.500000,,4.104287,,2.882746,,0.000000,,0.149931,,0.000000,,
  24,0.887136,,0.112864,,1.000000,,8.208574,,0.000000,,0.000000,,0.000000,,0.000000,,
  25,0.887136,,0.112864,,1.000000,,6.208574,,0.000000,,0.000000,,0.000000,,0.000000,,
  26,0.688867,,0.311133,,0.270470,,2.404181,,3.745432,,0.000000,,0.606253,,0.000000,,
  27,0.688867,,0.311133,,0.500000,,3.595819,,1.000000,,0.000000,,0.161865,,0.000000,,

FF,copo,cop1,b,B,c,C　－TP21ー
   1,0.500000,,0.500000,,0.911801,,0.000000,,0.000000,,0.000000,,0.000000,,0.000000,,
   2,0.500000,,0.500000,,0.404218,,1.000000,,0.000000,,0.000000,,0.000000,,0.000000,,
   3,0.500000,,0.500000,,0.688867,,1.000000,,0.000000,,0.000000,,0.000000,,0.000000,,
   4,0.500000,,0.500000,,0.153567,,1.000000,,0.000000,,0.000000,,0.000000,,0.000000,,
   5,0.112864,,0.887136,,1.000000,,8.242752,,0.000000,,0.000000,,0.000000,,0.000000,,
   6,0.545968,,0.454032,,1.000000,,1.000000,,0.000000,,0.000000,,0.000000,,0.000000,,
   7,0.808064,,0.191936,,1.000000,,1.000000,,0.000000,,0.000000,,0.000000,,0.000000,,
   8,0.622266,,0.377734,,1.000000,,1.000000,,0.000000,,0.000000,,0.000000,,0.000000,,
   9,0.500000,,0.500000,,0.911801,,2.000000,,0.000000,,0.000000,,0.000000,,0.000000,,
  10,0.093086,,0.906914,,1.000000,,8.242752,,0.000000,,0.000000,,0.000000,,0.000000,,
  11,0.904032,,0.095968,,0.273526,,4.109441,,1.000000,,0.000000,,0.043816,,0.000000,,
  12,0.688866,,0.311134,,0.299182,,7.407580,,0.000000,,5.371822,,0.000000,,2.723798,,
  13,0.452016,,0.547984,,0.169869,,4.199300,,0.000000,,8.149614,,0.000000,,2.128941,,
  14,0.170496,,0.829504,,0.545968,,12.606880,,1.000000,,0.000000,,0.768285,,0.000000,,
  15,0.546543,,0.453457,,1.000000,,9.011935,,0.000000,,0.000000,,0.000000,,0.000000,,
  16,0.906914,,0.093086,,1.000000,,15.606880,,2.882746,,0.000000,,0.122325,,0.000000,,
  17,0.688867,,0.311133,,0.649591,,4.000000,,4.745432,,0.000000,,0.768118,,0.000000,,
  18,0.655566,,0.344434,,1.000000,,6.502561,,0.000000,,0.000000,,0.000000,,0.000000,,
  19,0.500000,,0.500000,,0.052500,,1.109441,,0.000000,,1.000000,,0.000000,,0.301030,,
  20,0.500000,,0.500000,,0.906914,,2.890559,,4.104287,,0.000000,,1.235514,,0.000000,,
  21,0.999999,,0.000001,,0.206096,,3.910141,,2.404181,,0.000000,,0.000001,,0.000000,,
  22,0.904032,,0.095968,,0.084935,,2.199300,,1.000000,,0.000000,,0.043816,,0.000000,,
  23,0.906914,,0.093086,,0.500000,,4.121376,,2.882746,,0.000000,,0.122325,,0.000000,,
  24,0.906914,,0.093086,,1.000000,,8.242752,,0.000000,,0.000000,,0.000000,,0.000000,,
  25,0.906914,,0.093086,,1.000000,,6.242752,,0.000000,,0.000000,,0.000000,,0.000000,,
  26,0.688867,,0.311133,,0.299181,,2.497439,,3.745432,,0.000000,,0.606253,,0.000000,,
  27,0.688867,,0.311133,,0.500000,,3.502561,,1.000000,,0.000000,,0.161865,,0.000000,,

**Comment by Aono082** [comment]
[s27_reference_multi(hybrid_init_ave_TP21).xlsx](https://github.com/ehimetakahashilab/Hybrid-TPI/files/3895270/s27_reference_multi.hybrid_init_ave_TP21.xlsx)

よさそう

**Comment by Aono082** [comment]
とりあえず、分岐先のTPはサポートできたかな？
まだやることある？

**Comment by MaineK00n** [comment]
pushしてます？
こちらでしたほうがいいですか？

**Comment by MaineK00n** [comment]
データの更新とか？

**Comment by Aono082** [comment]
分岐先か分岐元かと言われたら
分岐元のほうがbBが大きくなって選ばれやすいのではないかと思う

分岐先はちゃんと選ばれるのだろうか

**Comment by MaineK00n** [comment]
`make all`書けたら，更新されてないみたいなんですけど…

**Comment by Aono082** [comment]
出力ファイルに変更がないということ？

**Comment by MaineK00n** [comment]
逆です
最新のcommitにcheckoutして，`make all`を実行したところ，出力ファイルに変更があったということです

**Comment by Aono082** [comment]
分かったわ
こっちでリファレンス作るときに
copの計算の差が無い時にスキップするという機能を無くしてたんよ

それが反映されたまま取ってしまったけん
そちらが正しいです

**Comment by MaineK00n** [comment]
了解です

**Comment by MaineK00n** [comment]
s27だとline:20が選ばれている？

```bash
$ ./htpi --mode 0 -n 3 s27
line:    1 , D:       0.000000 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:    2 , D:       1.000000 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:    3 , D:       1.000000 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:    4 , D:       1.000000 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:    5 , D:       7.469389 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:    6 , D:       1.000000 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:    7 , D:       1.000000 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:    8 , D:       1.000000 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:    9 , D:       2.000000 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:   10 , D:       7.469389 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:   11 , D:       4.693876 , b:       3.714285 , B:       0.000000 , c:       0.464058 , C:       0.000000 , TPI_flag:0
line:   12 , D:       7.530610 , b:       0.000000 , B:       5.371734 , c:       0.000000 , C:       0.000002 , TPI_flag:1
line:   13 , D:       4.877551 , b:       0.000000 , B:       8.216026 , c:       0.000000 , C:       0.000004 , TPI_flag:1
line:   14 , D:      13.408161 , b:       1.000000 , B:       0.000000 , c:       0.000001 , C:       0.000000 , TPI_flag:0
line:   15 , D:      10.775507 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:   16 , D:      16.408161 , b:       2.688836 , B:       0.000000 , c:       0.809418 , C:       0.000000 , TPI_flag:0
line:   17 , D:       4.000000 , b:       4.164300 , B:       0.000000 , c:       0.520282 , C:       0.000000 , TPI_flag:0
line:   18 , D:       6.285715 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:   19 , D:       1.693876 , b:       0.000000 , B:       1.000000 , c:       0.000000 , C:       0.301030 , TPI_flag:0
line:   20 , D:       2.306124 , b:       4.117552 , B:       0.000000 , c:       0.000002 , C:       0.000000 , TPI_flag:1
line:   21 , D:       3.816326 , b:       2.276596 , B:       0.000000 , c:       0.284435 , C:       0.000000 , TPI_flag:0
line:   22 , D:       2.877551 , b:       1.000000 , B:       0.000000 , c:       0.124939 , C:       0.000000 , TPI_flag:0
line:   23 , D:       6.469383 , b:       2.688836 , B:       0.000000 , c:       0.809418 , C:       0.000000 , TPI_flag:0
line:   24 , D:       7.469389 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:   25 , D:       5.469389 , b:       0.000000 , B:       0.000000 , c:       0.000000 , C:       0.000000 , TPI_flag:0
line:   26 , D:       2.714285 , b:       3.164300 , B:       0.000000 , c:       0.395344 , C:       0.000000 , TPI_flag:0
line:   27 , D:       3.285715 , b:       1.000000 , B:       0.000000 , c:       0.124939 , C:       0.000000 , TPI_flag:0
```

**Comment by MaineK00n** [comment]
これだと12, 13に入ってしまって，TP同士が相互干渉してそうですね

**Comment by Aono082** [comment]
この12と13が
ちょうど、前話してたケースやな
12を制御しても13に影響が出ないから
次に13が選ばれてしまう

**Comment by Aono082** [comment]
シミュレーション回す前に先にこの問題を少し考えるか

**Comment by MaineK00n** [comment]
これがHybrid-TPIを再現するものなら，ここに手は入れれない気もしますが

**Comment by Aono082** [comment]
たしかに、シミュレーション回すわ

**Comment by MaineK00n** [comment]
Mergeしませんか？

**Pull request merged**
