### PR TITLE
ほしい出力ファイルを揃える

### PR DESCRIPTION
**Pull request by Aono082**
## WHY
故障シミュレーションを行うため

## WHAT
以下の出力ファイルを出す
- 初期値0.5(hybrid_tpi)
- 初期値cop_ave(hybrid_tpi_init_ave)
- 初期値cop_ave+PRPF入力(hybrid_tpi_init_ave_PRPF)
- 初期値cop_ave+PRPF_PO入力(hybrid_tpi_init_ave_PRPF_PO)

## REF
#47

### CODE REVIEW

**Comment by Aono082** [comment]
[s27_reference_hybrid_FF_init_0.5.xlsx](https://github.com/ehimetakahashilab/Hybrid-TPI/files/3818126/s27_reference_hybrid_FF_init_0.5.xlsx)

./htpi -n 2 s27

gate cop0 cop1 copO D b_0 b_1 c_0 c_1
1 0.500000 0.500000 0.885027 0.000000 0.000000 0.000000 0.000000 0.000000
2 0.500000 0.500000 0.308594 1.000000 0.000000 0.000000 0.000000 0.000000
3 0.500000 0.500000 0.750000 1.000000 0.000000 0.000000 0.000000 0.000000
4 0.500000 0.500000 0.164062 1.000000 0.000000 0.000000 0.000000 0.000000
5 0.136719 0.863281 1.000000 8.235104 0.000000 0.000000 0.000000 0.000000
6 0.500000 0.500000 1.000000 1.000000 0.000000 0.000000 0.000000 0.000000
7 0.500000 0.500000 1.000000 1.000000 0.000000 0.000000 0.000000 0.000000
8 0.500000 0.500000 1.000000 1.000000 0.000000 0.000000 0.000000 0.000000
9 0.500000 0.500000 0.885027 2.000000 0.000000 0.000000 0.000000 0.000000
10 0.136719 0.863281 1.000000 8.235104 0.000000 0.000000 0.000000 0.000000
11 0.750000 0.250000 0.318115 4.311164 3.276596 0.000000 0.409374 0.000000
12 0.562500 0.437500 0.312500 7.216026 0.000000 5.371734 0.000000 1.928570
13 0.375000 0.625000 0.218750 4.371734 0.000000 8.216026 0.000000 1.677055
14 0.273438 0.726562 0.500000 12.587760 1.000000 0.000000 0.563142 0.000000
15 0.568359 0.431641 1.000000 8.806388 0.000000 0.000000 0.000000 0.000000
16 0.863281 0.136719 1.000000 15.587760 2.688836 0.000000 0.171676 0.000000
17 0.750000 0.250000 0.617188 4.000000 4.939430 0.000000 0.617126 0.000000
18 0.625000 0.375000 1.000000 6.723404 0.000000 0.000000 0.000000 0.000000
19 0.500000 0.500000 0.159058 1.311164 0.000000 0.000000 0.000000 0.000000
20 0.500000 0.500000 0.863281 2.688836 0.000000 0.000000 0.000000 0.000000
21 0.750000 0.250000 0.234375 3.939430 0.000000 0.000000 0.000000 0.000000
22 0.750000 0.250000 0.109375 2.371734 0.000000 0.000000 0.000000 0.000000
23 0.863281 0.136719 0.500000 4.117552 0.000000 0.000000 0.000000 0.000000
24 0.863281 0.136719 1.000000 8.235104 0.000000 0.000000 0.000000 0.000000
25 0.863281 0.136719 1.000000 6.235104 0.000000 0.000000 0.000000 0.000000
26 0.750000 0.250000 0.234375 2.276596 0.000000 0.000000 0.000000 0.000000
27 0.750000 0.250000 0.500000 3.723404 0.000000 0.000000 0.000000 0.000000

1回目 -TP 12- set1
gate cop0 cop1 copO D b_0 b_1 c_0 c_1
1 0.500000 0.500000 0.754029 0.000000 0.000000 0.000000 0.000000 0.000000
2 0.500000 0.500000 0.308594 1.000000 0.000000 0.000000 0.000000 0.000000
3 0.500000 0.500000 0.750000 1.000000 0.000000 0.000000 0.000000 0.000000
4 0.500000 0.500000 0.375000 1.000000 0.000000 0.000000 0.000000 0.000000
5 0.136719 0.863281 1.000000 8.299792 0.000000 0.000000 0.000000 0.000000
6 0.500000 0.500000 1.000000 1.000000 0.000000 0.000000 0.000000 0.000000
7 0.500000 0.500000 1.000000 1.000000 0.000000 0.000000 0.000000 0.000000
8 0.500000 0.500000 1.000000 1.000000 0.000000 0.000000 0.000000 0.000000
9 0.500000 0.500000 0.754029 2.000000 0.000000 0.000000 0.000000 0.000000
10 0.312500 0.687500 1.000000 8.299792 0.000000 0.000000 0.000000 0.000000
11 0.750000 0.250000 0.425781 4.472885 3.276596 0.000000 0.409374 0.000000
12 0.000001 0.999999 0.312500 6.440896 0.000000 5.371734 0.000000 0.000002
13 0.375000 0.625000 0.499999 5.308585 0.000000 8.216026 0.000000 1.677055
14 0.624999 0.375001 0.500000 12.749480 1.000000 0.000000 0.204120 0.000000
15 0.656250 0.343750 1.000000 8.677011 0.000000 0.000000 0.000000 0.000000
16 0.687500 0.312500 1.000000 15.749480 2.688836 0.000000 0.437546 0.000000
17 0.750000 0.250000 0.617188 4.000000 4.939430 0.000000 0.617126 0.000000
18 0.625000 0.375000 1.000000 6.723404 0.000000 0.000000 0.000000 0.000000
19 0.500000 0.500000 0.212891 1.472885 0.000000 0.000000 0.000000 0.000000
20 0.500000 0.500000 0.687500 2.527115 0.000000 0.000000 0.000000 0.000000
21 0.750000 0.250000 0.234375 3.164300 0.000000 0.000000 0.000000 0.000000
22 0.750000 0.250000 0.250000 3.308584 0.000000 0.000000 0.000000 0.000000
23 0.687500 0.312500 0.500000 4.149896 0.000000 0.000000 0.000000 0.000000
24 0.687500 0.312500 1.000000 8.299792 0.000000 0.000000 0.000000 0.000000
25 0.687500 0.312500 1.000000 6.299792 0.000000 0.000000 0.000000 0.000000
26 0.750000 0.250000 0.234375 2.276596 0.000000 0.000000 0.000000 0.000000
27 0.750000 0.250000 0.500000 3.723404 0.000000 0.000000 0.000000 0.000000

2回目 -TP 13- set1
gate cop0 cop1 copO D b_0 b_1 c_0 c_1
1 0.500000 0.500000 0.632813 0.000000 0.000000 0.000000 0.000000 0.000000
2 0.500000 0.500000 0.343750 1.000000 0.000000 0.000000 0.000000 0.000000
3 0.500000 0.500000 0.750000 1.000000 0.000000 0.000000 0.000000 0.000000
4 0.500000 0.500000 0.375000 1.000000 0.000000 0.000000 0.000000 0.000000
5 0.136719 0.863281 1.000000 8.563265 0.000000 0.000000 0.000000 0.000000
6 0.500000 0.500000 1.000000 1.000000 0.000000 0.000000 0.000000 0.000000
7 0.500000 0.500000 1.000000 1.000000 0.000000 0.000000 0.000000 0.000000
8 0.500000 0.500000 1.000000 1.000000 0.000000 0.000000 0.000000 0.000000
9 0.500000 0.500000 0.632813 2.000000 0.000000 0.000000 0.000000 0.000000
10 0.499999 0.500001 1.000000 8.563265 0.000000 0.000000 0.000000 0.000000
11 0.750000 0.250000 0.531250 4.693876 3.276596 0.000000 0.409374 0.000000
12 0.000001 0.999999 0.499999 7.530611 0.000000 5.371734 0.000000 0.000002
13 0.000001 0.999999 0.499999 4.877551 0.000000 8.216026 0.000000 0.000004
14 0.999998 0.000002 0.500000 13.408161 1.000000 0.000000 0.000001 0.000000
15 0.750000 0.250001 1.000000 8.587756 0.000000 0.000000 0.000000 0.000000
16 0.500001 0.499999 1.000000 16.408161 2.688836 0.000000 0.809418 0.000000
17 0.750000 0.250000 0.687500 4.000000 4.939430 0.000000 0.617126 0.000000
18 0.625000 0.375000 1.000000 6.285715 0.000000 0.000000 0.000000 0.000000
19 0.500000 0.500000 0.265625 1.693876 0.000000 0.000000 0.000000 0.000000
20 0.500000 0.500000 0.500001 2.306124 0.000000 0.000000 0.000000 0.000000
21 0.750000 0.250000 0.375000 3.816326 0.000000 0.000000 0.000000 0.000000
22 0.750000 0.250000 0.250000 2.877551 0.000000 0.000000 0.000000 0.000000
23 0.500001 0.499999 0.500000 4.281632 0.000000 0.000000 0.000000 0.000000
24 0.500001 0.499999 1.000000 8.563265 0.000000 0.000000 0.000000 0.000000
25 0.500001 0.499999 1.000000 6.563264 0.000000 0.000000 0.000000 0.000000
26 0.750000 0.250000 0.375000 2.714285 0.000000 0.000000 0.000000 0.000000
27 0.750000 0.250000 0.500000 3.285715 0.000000 0.000000 0.000000 0.000000

**Comment by Aono082** [comment]
値は合った
あとは、recalcの計算が最適なルートをたどっているかを見たい

**Comment by Aono082** [comment]
このプルリク残したままで、ブランチ#47は破壊していい？

**Comment by MaineK00n** [comment]
これはmasterにmergeしなくていいのですか？

**Comment by MaineK00n** [comment]
`FLT_LIST`に更新があるみたいですが…

**Comment by Aono082** [comment]
まだほとんど触ってないけん
今のmasterから作り直したい

または、このブランチ#47にmasterをマージしたい

**Comment by MaineK00n** [comment]
> まだほとんど触ってないけん
> 今のmasterから作り直したい
>
> または、このブランチ#47にmasterをマージしたい

いまやってますので，待ってほしいです

**Comment by MaineK00n** [comment]
> > まだほとんど触ってないけん
> > 今のmasterから作り直したい
> > または、このブランチ#47にmasterをマージしたい
> 
> いまやってますので，待ってほしいです

終わった

**Comment by Aono082** [comment]
どもー

**Comment by Aono082** [comment]
まあまあ雑に作った
何かいい方法あればそのうちやる

**Comment by MaineK00n** [comment]
`MODE`がオプションで渡せるとよい？

**Comment by Aono082** [comment]
とりあえずマージしたんでよい？

**Comment by Aono082** [comment]
outputにファイルがそろってないw
makeするたびに消えるんか

**Comment by MaineK00n** [comment]
> 
> 
> `MODE`がオプションで渡せるとよい？

`options.mode`を追加
cmdでは`--mode`で指定可能

**Comment by MaineK00n** [comment]
> 
> 
> outputにファイルがそろってないw
> makeするたびに消えるんか

各MODEで出力されるファイルを追加

**Pull request merged**
